# Generated by Django 3.1.2 on 2020-11-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('post_info', models.TextField()),
                ('slug', models.SlugField(default=None, unique=True)),
                ('date', models.DateTimeField(default=None)),
                ('url_field', models.URLField(default=None)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
