# Generated by Django 3.1.3 on 2020-11-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_app', '0002_auto_20201114_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='age',
            field=models.PositiveIntegerField(blank=20),
        ),
    ]
