# Generated by Django 3.1.3 on 2020-11-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_app', '0003_auto_20201114_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(upload_to='cars'),
        ),
    ]
