# Generated by Django 3.1.3 on 2020-11-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_app', '0004_auto_20201115_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
